In [1]:
! pip install quantecon
! pip install nashpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.8/214.8 kB 5.0 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Tian Ji's Horse Racing Game and Strategy

Tian Ji's Horse Racing is a game that follows the following rule: Tian Ji and the king of the Qi Kingdom are the two players in this game. The king of possesses superior horses than Tian Ji. In each round of the game, Tian Ji and the king both select three horses, categorizing them as good, better, and best. The race operates under the rule of three rounds, with the victor being the one who wins at least two rounds. Here is the game matrix for Tian Ji.

|            | ABC   | ACB   | BAC   | BCA   | CAB   | CBA   |
|------------|-------|-------|-------|-------|-------|-------|
| ABC        | -1, 1 | -1, 1 | -1, 1 | 1, -1 | -1, 1 | -1, 1 |
| ACB        | -1, 1 | -1, 1 | 1, -1 | -1, 1 | -1, 1 | -1, 1 |
| BAC        | -1, 1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 | 1, -1 |
| BCA        | -1, 1 | -1, 1 | -1, 1 | -1, 1 | 1, -1 | -1, 1 |
| CAB        | 1, -1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 |
| CBA        | -1, 1 | 1, -1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 |

Tian Ji (T) and King (K) use the following strategy in horse racing:

- T's "good" horse (C) races against K's "best" horse (A).
- T's "best" horse (A) races against K's "better" horse (B).
- T's "better" horse (B) races against K's "good" horse (C).

This strategy allows Tian Ji to win the race by losing the first round but winning the second and third rounds.


#Penalty Kick Game Based on Horse Racing Game

## Game Description of The Penalty Game:
The Penalty kick game simulates the penalty shoot-out in real football games. This game combines the real world football senarios and the Tian Ji's horse racing game. This game follows the following rule: two coaches in two different football teams are the two players in this game. One team's player is better than the other team. In each game, two coaches both select three players. The player has different levels, which are low(L), middle(M), and high(H). The game operates under the rule of three rounds, with the victor being the one who first wins two rounds. Here is the game matrix for the week team.

|            | HML   | HLM   | MHL   | MLH   | LHM   | LMH   |
|------------|-------|-------|-------|-------|-------|-------|
| HML        | -1, 1 | -1, 1 | -1, 1 | 1, -1 | -1, 1 | -1, 1 |
| HLM        | -1, 1 | -1, 1 | 1, -1 | -1, 1 | -1, 1 | -1, 1 |
| MHL        | -1, 1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 | 1, -1 |
| MLH        | -1, 1 | -1, 1 | -1, 1 | -1, 1 | 1, -1 | -1, 1 |
| LHM        | 1, -1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 |
| LMH        | -1, 1 | 1, -1 | -1, 1 | -1, 1 | -1, 1 | -1, 1 |


## Code Solution for The Penalty Game

In [2]:
# Code Solution using Nash Equilibrium
import nashpy as nash
import numpy as np

# Create the matrix
A = np.array([[-1, -1, -1, 1, -1, -1], [-1, -1, 1, -1, -1, -1],[-1, -1, -1, -1, -1, 1],[-1, -1, -1, -1, 1, -1],[1, -1, -1, -1, -1, -1],[-1, 1, -1, -1, -1, -1]])
B = np.array([[1, 1, 1, -1, 1, 1], [1, 1, -1, 1, 1, 1],[1, 1, 1, 1, 1, -1],[1, 1, 1, 1, -1, 1],[-1, 1, 1, 1, 1, 1],[1, -1, 1, 1, 1, 1]])

# Create the game
penalty = nash.Game(A, B)
penalty


Zero sum game with payoff matrices:

Row player:
[[-1 -1 -1  1 -1 -1]
 [-1 -1  1 -1 -1 -1]
 [-1 -1 -1 -1 -1  1]
 [-1 -1 -1 -1  1 -1]
 [ 1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1]]

Column player:
[[ 1  1  1 -1  1  1]
 [ 1  1 -1  1  1  1]
 [ 1  1  1  1  1 -1]
 [ 1  1  1  1 -1  1]
 [-1  1  1  1  1  1]
 [ 1 -1  1  1  1  1]]

In [3]:
# Find the Nash equilibrium
equilibria = penalty.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667]), array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667]))


## Description of The Solution

From the game description, the coach of the weak team and the coach of the strong team have different strategies to choose from. Let's analyze the week team coach's (W) strategy in response to the strong team coach's (S) choices:

- If the S chooses HML, W can choose LHM.
- If the S chooses HLM, W can choose LMH.
- If the S chooses MHL, W can choose HLM.
- If the S chooses MLH, W can choose HML.
- If the S chooses LHM, W can choose MLH.
- If the S chooses LMH, W can choose MHL.

Based on these strategies, W can select the corresponding option that brings him the maximum benefit, depending on S's choice. It is important to note that none of these strategies are mutual best responses, and thus, there is no pure Nash equilibrium strategy in the game.

From the code solution, a mixed Nash equilibrium strategy exists. If W does not know the strategy of the other team, both players can change their strategies. The dominant strategy for S is to choose randomly. Regardless of the strategy he chooses, the probability for S to win is 5/6. The expected payoff for S is 5/6. Similarly, the dominant strategy for W is also to choose randomly since the probability for W to win is 1/6. The expected payoff for W is -5/6. Therefore, in the absence of knowledge about the opponent's strategy, the dominant strategy for both Teams is to choose randomly.

# Penalty Kick Game With Shooting Probability
## Game Description of The Penalty Game:
In real-world scenarios, there is a possibility that the player misses the goal. Based on the situation, the game sets the probability of shooting as follows:
- Week team: High-level(80%), Middle-level(60%), Low-Level(40%)
- Strong team: High-level(90%), Middle-level(70%), Low-Level(50%)

Thus, the game matrix is as follows:

|            | HML   | HLM   | MHL   | MLH   | LHM   | LMH   |
|------------|-------|-------|-------|-------|-------|-------|
| HML        | -2.1, 2.1 | -1, 1 | -0.6, 0.6 | 0.5, -0.5 | -0.8, 0.8 | -0.8, 0.8 |
| HLM        | -1, 1 | -2.1, 2.1 | 0.5, -0.5 | -0.6, 0.6 | -0.8, 0.8 | -0.8, 0.8 |
| MHL        | -0.6, 0.6 | -0.8, 0.8 | -2.1, 2.1 | -0.8, 0.8 | -1, 1 | 0.5, -0.5 |
| MLH        | -0.8, 0.8 | -0.6, 0.6 | -0.8, 0.8 | -2.1, 2.1 | 0.5, -0.5 | -1, 1 |
| LHM        | 0.5, -0.5 | -0.8, 0.8 | -1, 1 | -0.8, 0.8 | -2.1, 2.1 | -0.6, 0.6 |
| LMH        | -0.8, 0.8 | 0.5, -0.5 | -0.8, 0.8 | -1, 1 | -0.6, 0.6 | -2.1, 2.1 |

##Coding Solution

In [4]:
# Code Solution using Nash Equilibrium
import nashpy as nash
import numpy as np

# Create the matrix
A = np.array([[-2.1, -1, -0.6, 0.5, -0.8, -0.8], [-1, -2.1, 0.5, -0.6, -0.8, -0.8],[-0.6, -0.8, -2.1, -0.8, -1, 0.5],[-0.8, -0.6, -0.8, -2.1, 0.5, -1],[0.5, -0.8, -1, -0.8, -2.1, -0.6],[-0.8, 0.5, -0.8, -1, -0.6, -2.1]])
B = np.array([[2.1, 1, 0.6, -0.5, 0.8, 0.8], [1, 2.1, -0.5, 0.6, 0.8, 0.8],[0.6, 0.8, 2.1, 0.8, 1, -0.5],[0.8, 0.6, 0.8, 2.1, -0.5, 1],[-0.5, 0.8, 1, 0.8, 2.1, 0.6],[0.8, -0.5, 0.8, 1, 0.6, 2.1]])

# Create the game
penalty_p = nash.Game(A, B)
penalty_p

Zero sum game with payoff matrices:

Row player:
[[-2.1 -1.  -0.6  0.5 -0.8 -0.8]
 [-1.  -2.1  0.5 -0.6 -0.8 -0.8]
 [-0.6 -0.8 -2.1 -0.8 -1.   0.5]
 [-0.8 -0.6 -0.8 -2.1  0.5 -1. ]
 [ 0.5 -0.8 -1.  -0.8 -2.1 -0.6]
 [-0.8  0.5 -0.8 -1.  -0.6 -2.1]]

Column player:
[[ 2.1  1.   0.6 -0.5  0.8  0.8]
 [ 1.   2.1 -0.5  0.6  0.8  0.8]
 [ 0.6  0.8  2.1  0.8  1.  -0.5]
 [ 0.8  0.6  0.8  2.1 -0.5  1. ]
 [-0.5  0.8  1.   0.8  2.1  0.6]
 [ 0.8 -0.5  0.8  1.   0.6  2.1]]

In [5]:
# Find the Nash equilibrium
equilibria = penalty_p.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.33333333]), array([0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.33333333]))


## Description of The Solution

Though the payoff has changed, the weak team coach's (W) strategy in response to the strong team coach's (S) choices is still the same, which is similar to Tian Ji's strategy. It is because the weak team has only one strategy out of six to win over the strong team. Besides, there is still no pure Nash equilibrium strategy in the game. The strategy is as follows:

- If the S chooses HML, W can choose LHM.
- If the S chooses HLM, W can choose LMH.
- If the S chooses MHL, W can choose HLM.
- If the S chooses MLH, W can choose HML.
- If the S chooses LHM, W can choose MLH.
- If the S chooses LMH, W can choose MHL.


From the code solution, the mixed Nash equilibrium strategy has changed along with the change in the payoff. The dominant strategy for S is to choose randomly from HLM, MHL, and LMH. The probability for S to win is 2/3. The expected payoff is 7/10. The dominant strategy for W is also to choose randomly from HLM, MHL, and LMH. The probability for W to win is 1/3. The expected payoff is -7/10.